# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/root/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
flags: {}
extra-package-dbs: []
packages: []
resolver: lts-7.16
extra-deps:
  - yaml-light-0.1.4
  - HsSyck-0.53
  - HDBC-postgresql-2.3.2.5
  - dbmigrations-2.0.0
